apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    spec:
      volumes:
        - name: volume-pricing-service
      containers:
        - resources:
            limits:
              cpu: 120m
              memory: 384Mi
            requests:
              cpu: 60m
              memory: 256Mi
          image: leosthewarregistry.azurecr.io/pricing-service:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: volume-pricing-service
              mountPath: /data
          name: pricing-service
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
    metadata:
      labels:
        app: pricing-service
